name: fat_dev
description: development tools
version: 0.0.1
author: Phat <damphat@gmail.com>
homepage: https://github.com/damphat/fat_dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
